sparse-small:
    nmslib1:
      docker-tag: neurips23-sparse-nmslib
      module: neurips23.sparse.nmslib.nmslib
      constructor: SparseNMSLIB
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"M": 32, "efConstruction": 512, "buildthreads": 8}]
          query-args: 
            [[32,64,128,256]]
sparse-1M:
    nmslib_efc256:
      docker-tag: neurips23-sparse-nmslib
      module: neurips23.sparse.nmslib.nmslib
      constructor: SparseNMSLIB
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"M": 32, "efConstruction": 256, "buildthreads": 8}]
          query-args: 
            [[32,64,128,256]]
sparse-full:
    nmslib_efc256:
      docker-tag: neurips23-sparse-nmslib
      module: neurips23.sparse.nmslib.nmslib
      constructor: SparseNMSLIB
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"M": 32, "efConstruction": 256, "buildthreads": 8}]
          query-args: 
            [[32,64,128,256]]
    nmslib_efc512:
      docker-tag: neurips23-sparse-nmslib
      module: neurips23.sparse.nmslib.nmslib
      constructor: SparseNMSLIB
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"M": 32, "efConstruction": 512, "buildthreads": 8}]
          query-args: 
            [[32,64,128,256,512]]
    nmslib_efc1024:
      docker-tag: neurips23-sparse-nmslib
      module: neurips23.sparse.nmslib.nmslib
      constructor: SparseNMSLIB
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"M": 32, "efConstruction": 1024, "buildthreads": 8}]
          query-args: 
            [[32,64,128,256,512]]