sparse-small:
    lucene:
      docker-tag: neurips23-sparse-lucene
      module: neurips23.sparse.lucene.lucene
      constructor: SparseNMSLIB
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"M": 32, "efConstruction": 512, "buildthreads": 8}]
          query-args: 
            [[32,64,128,256]]
sparse-1M:
    lucene:
      docker-tag: neurips23-sparse-lucene
      module: neurips23.sparse.lucene.lucene
      constructor: SparseNMSLIB
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"M": 32, "efConstruction": 256, "buildthreads": 8}]
          query-args: 
            [[32,64,128,256]]