sparse-small:
    lucene:
      docker-tag: neurips23-sparse-lucene
      module: neurips23.sparse.lucene.lucene
      constructor: LuceneEngine
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"x": 1}]
          query-args: 
            [[1]]
sparse-1M:
    lucene:
      docker-tag: neurips23-sparse-lucene
      module: neurips23.sparse.lucene.lucene
      constructor: LuceneEngine
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"x": 1}]
          query-args: 
            [[1]]
sparse-full:
    lucene:
      docker-tag: neurips23-sparse-lucene
      module: neurips23.sparse.lucene.lucene
      constructor: LuceneEngine
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"x": 1}]
          query-args: 
            [[1]]